#!/bin/bash

echo "Runnig first boot setup..."

# Set timezone
if [ ! -z "${TZ}" ]; then
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
fi

# Disable boot service
touch /etc/service/boot/down
sv down boot 
